apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NagineniHari/EKS-argoCD.git
    targetRevision: main
    path: namespaces
  destination:
    server: https://kubernetes.default.svc   # Current Cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true # if you delete from Git, argocd also deletes it from cluster
      selfHeal: true # Revert the changes that were done manually in cluster, to sync git repo
